### ISSUE TITLE
nrf52840 build failed `psa/crypto.h: No such file or directory`

### ISSUE THREAD

**Issue by karthick-grl** [openthread/ot-reference-release#10]
_Note: Not sure if i should raise the ticket here or `ot-nrf528xx` repo. If it should be raised in `ot-nrf528xx` please let me know i will close the ticket here and reopen there._  

Steps to reproduce the issue,
Run command:
`REFERENCE_PLATFORM=nrf52840 REFERENCE_RELEASE_TYPE=certification IN_CHINA=0  ./script/make-reference-release.bash`

Error log: 
![image](https://user-images.githubusercontent.com/12555028/137920655-c5d0c5e0-2e79-4a3e-b921-d07e53dd1cd3.png)

FYI, if it helps:
- Issue appeared after the recent merge of PR, which has updated the `ot-nrf528xx` submodule commit. 
- Although I could see `crypto.h` file under `.../ot-nrf528xx/openthread/third_party/mbedtls/repo/include/psa` build throws this error.

**Comment by siddhesh-grl** [comment]
The error exists because a flag 'OPENTHREAD_CONFIG_BORDER_ROUTER_ENABLE' in the code is set to '0'.
To remove the error :
1) cd to the below mentioned directory : 
cd <ot-reference-release root directory>/ot-nrf528xx/openthread/src/core/config/
2) Open the border_router.h file
3) Change the `#define OPENTHREAD_CONFIG_BORDER_ROUTER_ENABLE 0` line to `#define OPENTHREAD_CONFIG_BORDER_ROUTER_ENABLE 1` 
![ENABLE_THE_BR](https://user-images.githubusercontent.com/93367257/139809372-2b194246-0850-4f7e-aa5e-08178a34be2f.png)
4) Then run the 'make-reference-release.bash' script as indicated in the README

**Comment by siddhesh-grl** [comment]
The 'variable not declared' error exists because a flag 'OPENTHREAD_CONFIG_BORDER_ROUTER_ENABLE' in the code is set to '0'.
To remove the error :

1) cd to the below mentioned directory :
cd `<ot-reference-release root directory>/ot-nrf528xx/openthread/src/core/config/`
2) Open the border_router.h file
3) Change the `#define OPENTHREAD_CONFIG_BORDER_ROUTER_ENABLE 0` line to `#define OPENTHREAD_CONFIG_BORDER_ROUTER_ENABLE 1`
Refer the below mentioned screenshot, line number 56 for the same
![BR_ENABLING](https://user-images.githubusercontent.com/93367257/139810494-940d7327-1b83-4447-83d4-0104a9995617.png)

4) Then run the 'make-reference-release.bash' script as indicated in the README

**Comment by simonlingoogle** [comment]
> The 'variable not declared' error exists because a flag 'OPENTHREAD_CONFIG_BORDER_ROUTER_ENABLE' in the code is set to '0'.

Should not be compiling Publisher if it's not Border Router? @abtink

**Comment by abtink** [comment]
Thanks @simonlingoogle.  I think the enabling `BORDER_ROUTER_ENABLE` would address the build issue. 

We can use `NetworkData::Publisher` for service entries only when `NETDATA_SERVICE_ENABLE` is enabled and without `BORDER_ROUTER_ENABLE` being enabled.  Though I don't think/expect this config combination will be practically used. 

We have this check in `networkdata_publisher.hpp` already:
```c++
#if !OPENTHREAD_CONFIG_TMF_NETDATA_SERVICE_ENABLE && !OPENTHREAD_CONFIG_BORDER_ROUTER_ENABLE
#error "OPENTHREAD_CONFIG_NETDATA_PUBLISHER_ENABLE requires either OPENTHREAD_CONFIG_TMF_NETDATA_SERVICE_ENABLE"\
            "or OPENTHREAD_CONFIG_BORDER_ROUTER_ENABLE"
#endif
```

I think there was some missing `#if` check in the `cpp` file to allow this combo. I submitted 
- https://github.com/openthread/openthread/pull/7132

**Comment by jwhui** [comment]
FYI - https://github.com/openthread/openthread/pull/7132 has been merged.
